public enum SceneID
{
    Demo              = 1,
    Bootstrap         = 2,
    Hospital1         = 3,
    Hospital2         = 4,
    Hospital3         = 5,
    Counter           = 6,
    ConvenienceStore  = 7,
    ElevatorHallway   = 8,
    Lobby             = 9,
    Corridor          = 10,
    Kitchen           = 11,
    Terrace           = 12,
    GroceryStorage    = 13,
    EmployeeBreakroom = 14,
    Cafeteria         = 15,
    Office            = 16,
    PretreatmentRoom  = 17,
    HumanStorage      = 18,
}
